AWSTemplateFormatVersion: 2010-09-09
Description: Network Management
Resources:
  CorpVPC:
    Type: "AWS::EC2::VPC"
    Properties: 
      CidrBlock: !Ref CorpVPCCidrBlock
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: CorpVPC
  CorpInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: CorpInternetGateway
  CorpVPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref CorpVPC
      InternetGatewayId: !Ref CorpInternetGateway
  CorpPublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref CorpVPC
      CidrBlock: !Ref CorpPublicSubnet1CidrBlock
      AvailabilityZone: !Ref AvailabilityZone1
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: CorpPublicSubnet1
  CorpPublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref CorpVPC
      CidrBlock: !Ref CorpPublicSubnet2CidrBlock
      AvailabilityZone: !Ref AvailabilityZone2
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: CorpPublicSubnet2
  CorpPublicSubnet3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref CorpVPC
      CidrBlock: !Ref CorpPublicSubnet3CidrBlock
      AvailabilityZone: !Ref AvailabilityZone3
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: CorpPublicSubnet3
  CorpPublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref CorpVPC
      Tags:
        - Key: Name
          Value: CorpPublicRouteTable
  CorpPublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: ["CorpVPCGatewayAttachment"]
    Properties:
      RouteTableId: !Ref CorpPublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref CorpInternetGateway
  CorpPublicSubnet1RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref CorpPublicSubnet1
      RouteTableId: !Ref CorpPublicRouteTable
  CorpPublicSubnet2RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref CorpPublicSubnet2
      RouteTableId: !Ref CorpPublicRouteTable
  CorpPublicSubnet3RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref CorpPublicSubnet3
      RouteTableId: !Ref CorpPublicRouteTable
  CorpPublicNetworkAcl:
    Type: 'AWS::EC2::NetworkAcl'
    Properties:
      VpcId: !Ref CorpVPC
      Tags:
        - Key: Name
          Value: CorpPublicNetworkAcl
  CorpPublicNetworkAclEntryIngress1:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref CorpPublicNetworkAcl
      RuleNumber: '100'
      Protocol: '-1'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: 0.0.0.0/0
  CorpPublicNetworkAclEntryEgress1:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref CorpPublicNetworkAcl
      RuleNumber: '100'
      Protocol: '-1'
      RuleAction: allow
      Egress: 'true'
      CidrBlock: 0.0.0.0/0
  CorpPublicSubnet1NetworkAclAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      SubnetId: !Ref CorpPublicSubnet1
      NetworkAclId: !Ref CorpPublicNetworkAcl
  CorpPublicSubnet2NetworkAclAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      SubnetId: !Ref CorpPublicSubnet2
      NetworkAclId: !Ref CorpPublicNetworkAcl
  CorpPublicSubnet3NetworkAclAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      SubnetId: !Ref CorpPublicSubnet3
      NetworkAclId: !Ref CorpPublicNetworkAcl
Parameters:
  CorpVPCCidrBlock:
    Description: Corp VPC CIDR
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
  AvailabilityZone1:
    Description: AWS Availability Zone 1
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1a
  AvailabilityZone2:
    Description: AWS Availability Zone 2
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1b
  AvailabilityZone3:
    Description: AWS Availability Zone 3
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1c
  CorpPublicSubnet1CidrBlock:
    Description: Corp Public Subnet 1 CIDR
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
  CorpPublicSubnet2CidrBlock:
    Description: Corp Public Subnet 2 CIDR
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.1.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
  CorpPublicSubnet3CidrBlock:
    Description: Corp Public Subnet 3 CIDR
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.2.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "Network Management"
        Parameters:
          - CorpVPCCidrBlock
          - AvailabilityZone1
          - AvailabilityZone2
          - AvailabilityZone3
          - CorpPublicSubnet1CidrBlock
          - CorpPublicSubnet2CidrBlock
          - CorpPublicSubnet3CidrBlock
    ParameterLabels:
      CorpVPCCidrBlock:
        default: "VPC CIDR"
      AvailabilityZone1: 
        default: "Availability Zone1"
      AvailabilityZone2: 
        default: "Availability Zone2"
      AvailabilityZone3: 
        default: "Availability Zone3"
      CorpPublicSubnet1CidrBlock:
        default: "Public Subnet1 CIDR"
      CorpPublicSubnet2CidrBlock:
        default: "Public Subnet2 CIDR"
      CorpPublicSubnet3CidrBlock:
        default: "Public Subnet3 CIDR"